import React from "react"
const Equipment = {
  items: [
    {
      label: "Belts",
      content: (
        <ul>
          <li>
            <a
              target="_blank"
              rel="noreferrer"
              href="https://www.amazon.com/Fuji-BJJ-Belt-White-A4/dp/B00GIHZ2BQ/ref=sxin_7_ac_d_pm?ac_md=2-1-QmV0d2VlbiAkOSBhbmQgJDEw-ac_d_pm&cv_ct_cx=karate+white+belt&dchild=1&keywords=karate+white+belt&pd_rd_i=B00GIHZ2BQ&pd_rd_r=d7f9a84b-ff48-413a-bdb0-9b3be58d1f32&pd_rd_w=cCim9&pd_rd_wg=MnqwH&pf_rd_p=56b8ab64-8f22-43d4-8319-4b30f162b5e2&pf_rd_r=8MH72BNZT29C2HC2J919&psc=1&qid=1592336232&sr=1-2-22d05c05-1231-4126-b7c4-3e7a9c0027d0"
            >
              White
            </a>
          </li>
          <li>
            <a
              target="_blank"
              rel="noreferrer"
              href="https://www.amazon.com/Colored-Stripe-Martial-Karate-Taekwondo/dp/B0856RLCCZ/ref=sr_1_16?dchild=1&keywords=karate+white+yellow+belt&qid=1592336398&sr=8-16"
            >
              White-Yellow
            </a>
          </li>
          <li>
            <a
              target="_blank"
              rel="noreferrer"
              href="https://www.amazon.com/Fuji-Sports-Belt-Yellow-3/dp/B00GII02T2/ref=sr_1_5?dchild=1&keywords=karate+white+yellow+belt&qid=1592336398&sr=8-5"
            >
              Yellow
            </a>
          </li>
          <li>
            <a
              target="_blank"
              rel="noreferrer"
              href="https://www.amazon.com/Fuji-Sports-Belt-Orange-4/dp/B00GIHZQPS/ref=sr_1_10?dchild=1&keywords=karate+orange+belt&qid=1592336630&sr=8-10"
            >
              Orange
            </a>
          </li>
          <li>
            <a
              target="_blank"
              rel="noreferrer"
              href="https://www.amazon.com/Fuji-Sports-Belt-Green-1/dp/B00GIHZMXY/ref=sr_1_1?dchild=1&keywords=karate+green+belt&qid=1592336658&sr=8-1"
            >
              Green
            </a>
          </li>
          <li>
            <a
              target="_blank"
              rel="noreferrer"
              href="https://www.amazon.com/Fuji-BJJ-Belt-Purple-A2/dp/B00GIHYZAA/ref=sr_1_5?dchild=1&keywords=karate+purple+belt&qid=1592336678&sr=8-5"
            >
              Purple
            </a>
          </li>
          <li>
            <a
              target="_blank"
              rel="noreferrer"
              href="https://www.amazon.com/Fuji-Sports-Belt-Brown-5/dp/B00GIHZMV6/ref=sr_1_2?dchild=1&keywords=karate+brown+belt&qid=1592336697&sr=8-2"
            >
              Brown
            </a>
          </li>
          <li>
            <a
              target="_blank"
              rel="noreferrer"
              href="https://www.amazon.com/Fuji-Sports-Belt-Black-6/dp/B00GIHZELE/ref=sr_1_4?dchild=1&keywords=karate+black+belt&qid=1592336714&sr=8-4"
            >
              Black
            </a>
          </li>
        </ul>
      ),
    },
    {
      label: "Uniforms",
      content: (
        <div>
          <ul>
            <li>
              <a
                target="_blank"
                rel="noreferrer"
                href="https://www.amazon.com/ProForce-6oz-Student-Karate-Uniform/dp/B00AXDCNWC/ref=sxin_7_ac_d_rm?ac_md=1-1-a2FyYXRlIHVuaWZvcm0%3D-ac_d_rm&cv_ct_cx=karate+uniform+for+kids&dchild=1&keywords=karate+uniform+for+kids&pd_rd_i=B00AXDCNWC&pd_rd_r=cdb2e06b-d740-4d1d-a5d3-b75237bffb0d&pd_rd_w=y04GZ&pd_rd_wg=nUatW&pf_rd_p=a0516f22-66df-4efd-8b9a-279a864d1512&pf_rd_r=WF4630WC7E7N1NY537S1&psc=1&qid=1592337020&sr=1-2-12d4272d-8adb-4121-8624-135149aa9081"
              >
                Children
              </a>
            </li>
            <li>
              <a
                target="_blank"
                rel="noreferrer"
                href="https://www.amazon.com/Elite-Sports-Student-Uniform-Preshrunk/dp/B01N7HVF9X/ref=sr_1_5?crid=1J50QWOXCS1XQ&dchild=1&keywords=karate+uniform+for+teens&qid=1592337442&sprefix=karate+uniform+for+teen%2Caps%2C180&sr=8-5"
              >
                Youth
              </a>
            </li>
            <li>
              <a
                target="_blank"
                rel="noreferrer"
                href="https://www.amazon.com/NAMAZU-Uniform-Lightweight-Student-Training/dp/B07LBD1VL5/ref=sr_1_7?dchild=1&keywords=karate+uniform+for+adults&qid=1592337468&sr=8-7"
              >
                Adults
              </a>
            </li>
          </ul>
        </div>
      ),
    },
    {
      label: "Sparring Gear",
      content: (
        <ul>
          <a
            target="_blank"
            rel="noreferrer"
            href="https://www.amazon.com/Pro-Force-Lightning-Punches-Sparring/dp/B005E1AM8K/ref=sr_1_8?dchild=1&keywords=karate+gloves&qid=1592337857&sr=8-8"
          >
            <li>Gloves</li>
          </a>
          <a
            target="_blank"
            rel="noreferrer"
            href="https://www.amazon.com/Pro-Force-Lightning-Sparring-Headgear/dp/B005E1B0U4/ref=sr_1_3?dchild=1&keywords=karate+helmet&qid=1592338032&sr=8-3"
          >
            <li>Helmets</li>
          </a>
          <a
            target="_blank"
            rel="noreferrer"
            href="https://www.amazon.com/Pro-Force-Lightning-Sparring-Footgear/dp/B005E1C422/ref=sr_1_1?dchild=1&keywords=karate+foot+pads&qid=1592338056&sr=8-1"
          >
            <li>Footpads</li>
          </a>
          <a
            target="_blank"
            rel="noreferrer"
            href="https://www.amazon.com/EliteTek-Athletic-Groin-Protector-Supporters/dp/B07Y3W9GQ5/ref=sr_1_41?dchild=1&keywords=athletic+cup&qid=1592338075&sr=8-41"
          >
            <li>Cups</li>
          </a>
        </ul>
      ),
    },
  ],
}

export default Equipment
